apiVersion: apps/v1
kind: Deployment
metadata:
  name: exa-wn-ko-reg
  namespace: isfiligoi
  labels: 
    k8s-app: exa-wn-ko
spec:
  replicas: 8
  selector:
    matchLabels:
      k8s-app: exa-wn-ko
  template:
    metadata: 
      labels:
        k8s-app: exa-wn-ko
    spec:
      nodeSelector:
        kubernetes.io/hostname: dtn-gpu2.kreonet.net
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/noceph
        operator: Exists
      containers:
      - name: main
        image: sfiligoi/tnrp-net-tests:cloudburst2-wn
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        resources:
           limits:
             nvidia.com/gpu: 1
             memory: 20Gi
             cpu: 2
           requests:
             nvidia.com/gpu: 1
             memory: 15Gi
             cpu: 2
        volumeMounts:
        - name: configpasswd
          mountPath: /etc/condor/passwords.d/POOL
          subPath: POOL
          readOnly: true
        - name: configs3
          mountPath: /home/centos/.s3cfg
          subPath: .s3cfg
          readOnly: true
        - name: configlocal
          mountPath: /etc/condor/regions/prp_local.config
          subPath: prp_local.config
          readOnly: true
      volumes:
      - name: configpasswd
        secret:
          secretName: exa-pool-secret
          items:
             - key: POOL
               path: POOL
          defaultMode: 256
      - name: configs3
        secret:
          secretName: exa-s3-ko
          items:
             - key: .s3cfg
               path: .s3cfg
          defaultMode: 292 # all read is OK for this use case
      - name: configlocal
        secret:
          secretName: exa-s3-ko
          items:
             - key: prp_local.config
               path: prp_local.config
          defaultMode: 292 

