#!/bin/bash 
if [ $# -ne 2 ]; then
  echo "ERROR: Missing arguments" 1>&2
  echo "Usage: exa_cloud_download cloudpath localfile" 1>&2
  exit 1
fi

cloud_path=`exa_cloud_mangle "$1"`
if [ $? -ne 0 ]; then
  echo "ERROR: Failed parsing cloudpath: ${cloud_path}" 1>&2
  exit 1
fi

apath="$(realpath $2)"
dpath="$(dirname $apath)"
lpath="$(basename $apath)"

aria2c --max-tries=32 --retry-wait=1 -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
rc=$?
if [ $rc -ne 0 ]; then
  echo "ERROR: Download of ${cloud_path} failed." 2>&1
else
  echo "INFO: Downloaded ${cloud_path} into ${apath}" 2>&1
fi
exit $rc
