apiVersion: batch/v1
kind: Job
metadata:
  name: unifrac-nrp-300ks-8
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
              - key: env
                operator: In
                values:
                - nrp
      tolerations:
      - effect: NoSchedule
        key:  nautilus.io/nrp-testing
        operator: Exists
      containers:
      - name: test
        image: sfiligoi/unifrac
        command:
        - "/bin/bash"
        args:
        - "-l"
        - "-c"
        - "source /root/run_300k_small_8.sh"
        resources:
          limits:
            memory: 600Gi
            cpu: 64
            nvidia.com/gpu: 8
            ephemeral-storage: 160Gi
          requests:
            memory: 400Gi
            cpu: 30
            nvidia.com/gpu: 8
            ephemeral-storage: 130Gi
        volumeMounts:
        - mountPath: /root
          name: scratch
        - name: unifrac-nrp-script
          mountPath: /root/run_300k_small_8.sh
          subPath: run_300k_small_8.sh
        - name: unifrac-nrp-script2
          mountPath: /root/run_300k_support.sh
          subPath: run_300k_support.sh
      restartPolicy: Never
      volumes:
      - name: scratch
        emptyDir: {}
      - name: unifrac-nrp-script
        configMap:
          items:
          - key: run_300k_small_8.sh
            path: run_300k_small_8.sh
          name: unifrac-nrp-script
      - name: unifrac-nrp-script2
        configMap:
          items:
          - key: run_300k_support.sh
            path: run_300k_support.sh
          name: unifrac-nrp-script
