#!/bin/bash

# explicit path needed by gsutil
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ $# -ne 2 ]; then
  echo "ERROR: Missing arguments" 1>&2
  echo "Usage: exa_cloud_upload localfile cloudpath" 1>&2
  exit 1
fi

cloud_path=`exa_cloud_mangle "$2"`
if [ $? -ne 0 ]; then
  echo "ERROR: Failed parsing cloudpath: ${cloud_path}" 1>&2
  exit 1
fi

# GCP specific
# convert from http[s] to gcp notation
gcp_path=`echo "${cloud_path}" | sed 's#https://storage.googleapis.com/#gs://#'`

echo "INFO: Uploading to ${gcp_path} (${cloud_path})"
errstr=`gsutil cp "$1" "${gcp_path}" 2>&1`
rc=$?
if [ $rc -ne 0 ]; then
  sleep 1
  echo "INFO: Retrying upload"
  errstr=`gsutil cp "$1" "${gcp_path}" 2>&1`
  rc=$?
fi
if [ $rc -ne 0 ]; then
  sleep 5
  echo "INFO: Retrying upload"
  errstr=`gsutil cp "$1" "${gcp_path}" 2>&1`
  rc=$?
fi

if [ ${rc} -ne 0 ]; then
  echo "ERROR: Upload failed"
  echo "ERROR: Upload failed" 1>&2
  echo "$errstr" 1>&2
  exit 1
fi
exit 0

