#!/bin/bash
#SBATCH --exclusive
#SBATCH -t 12:00:00
hostname
lscpu
#echo "=============="
#rm -fr /tmp/igor
#mkdir -p /tmp/igor
#cp /projects/wol/release/databases/bowtie2/WoLr1* /tmp/igor/
#cp /qmounts/qiita_data/per_sample_FASTQ/88388/10317_000065377_S642_L003_R2_001.trimmed.fastq.gz /tmp/igor/
#ls -l /tmp/igor/
echo "=============="
cd /panfs/isfiligoi/t6/batch
source ../setup_conda.sh
conda activate unifrac-1.1.3
conda list
echo "=============="
md5sum merged_nosingletonsdoubletons_even500_sepp_nobloom_placement.tog.tre
md5sum merged_nosingletonsdoubletons_even500_nobloom.biom
export UNIFRAC_TIMING_INFO=Y
export OMP_NUM_THREADS=32
rm -f u_c3f.out
echo "=============="
time taskset -c 16-31,48-63 ssu -f -m unweighted_fp32 -i merged_nosingletonsdoubletons_even500_nobloom.biom -t merged_nosingletonsdoubletons_even500_sepp_nobloom_placement.tog.tre --pcoa 0  -r hdf5_fp32 -o ./u_c3f.out
echo "rc=$?"
md5sum u_c3f.out
rm -f u_c3f.out
echo "=============="
time taskset -c 16-31,48-63 ssu -f -m unweighted_fp32 -i merged_nosingletonsdoubletons_even500_nobloom.biom -t merged_nosingletonsdoubletons_even500_sepp_nobloom_placement.tog.tre --pcoa 0  -r hdf5_fp32 -o ./u_c3f.out
echo "rc=$?"
md5sum u_c3f.out
#rm -f u_c3f.out
#echo "=============="
#time taskset -c 16-31,48-63 ssu -f -m unweighted_fp32 -i merged_nosingletonsdoubletons_even500_nobloom.biom -t merged_nosingletonsdoubletons_even500_sepp_nobloom_placement.tog.tre --pcoa 0  -r hdf5_fp32 -o ./u_c3f.out
#echo "rc=$?"
#md5sum u_c3f.out
