#!/bin/bash
if [ $# -ne 2 ]; then
  echo "ERROR: Missing arguments" 1>&2
  echo "Usage: exa_cloud_upload localfile cloudpath" 1>&2
  exit 1
fi

cloud_path=`exa_cloud_mangle "$2"`
if [ $? -ne 0 ]; then
  echo "ERROR: Failed parsing cloudpath: ${cloud_path}" 1>&2
  exit 1
fi

# AWS specific
# convert from http[s] to s3 notation
s3_path=`echo "${cloud_path}" | sed 's/http.*:/s3:/' | sed 's/..3.amazonaws.com//'`

echo "INFO: Uploading to ${s3_path} (${cloud_path})"
errstr=`aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}" 2>&1`
rc=$?
if [ $rc -ne 0 ]; then
  sleep 1
  echo "INFO: Retrying upload"
  errstr=`aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}" 2>&1`
  rc=$?
fi
if [ $rc -ne 0 ]; then
  sleep 5
  echo "INFO: Retrying upload"
  errstr=`aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}" 2>&1`
  rc=$?
fi

if [ ${rc} -ne 0 ]; then
  echo "ERROR: Upload failed"
  echo "ERROR: Upload failed" 1>&2
  echo "$errstr" 1>&2
  exit 1
fi
exit 0

