apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: software
  namespace: fusion-psfc 
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
