apiVersion: v1
kind: Pod
metadata:
  name: login-small
  namespace: fusion-psfc 
spec:
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: nvidia.com/gpu.product
           operator: In
           values:
           - NVIDIA-A100-SXM4-80GB
  tolerations:
  - effect: NoSchedule
    key:  nautilus.io/nrp-testing
    operator: Exists
  containers:
  - name: mypod
    image: nvcr.io/nvidia/nvhpc:22.9-devel-cuda_multi-ubuntu20.04
    resources:
      limits:
        memory: 4Gi
        cpu: 2
        nvidia.com/gpu: 1
      requests:
        memory: 4Gi
        cpu: 0.2
        nvidia.com/gpu: 1
    command: ["sh", "-c", "/root/setup_node.sh; sleep 72000"]
    volumeMounts:
    - name: sw
      mountPath: /opt/fusion/software
    - name: setup-node
      mountPath: /root/setup_node.sh
      subPath: setup_node.sh
  volumes:
  - name: sw
    persistentVolumeClaim:
      claimName: software
  - name: setup-node
    configMap:
      items:
      - key: setup_node.sh
        path: setup_node.sh
      name: setup-scripts
      defaultMode: 320

