apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  nrp-provisioner-nrpnb-log-pvc
  namespace: osg-icecube
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
