apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsicecubesdsc6
  namespace: isfiligoi
  labels:
    nfslabel: nfsicecubesdsc6
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 132.249.108.146
    path: "/icecube-test"
