apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsicecubesdsc18
  namespace: isfiligoi
  labels:
    nfslabel: nfsicecubesdsc18
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 132.249.108.158
    path: "/icecube-test"
