#!/bin/bash
#SBATCH --exclusive
#SBATCH -t 24:00:00
hostname
lscpu
#echo "=============="
#rm -fr /tmp/igor
#mkdir -p /tmp/igor
#cp /projects/wol/release/databases/bowtie2/WoLr1* /tmp/igor/
#cp /qmounts/qiita_data/per_sample_FASTQ/88388/10317_000065377_S642_L003_R2_001.trimmed.fastq.gz /tmp/igor/
#ls -l /tmp/igor/
echo "=============="
cd /panfs/isfiligoi/t6/batch
source ../setup_conda.sh
conda activate unifrac-old
conda list
echo "=============="
md5sum emp90.5000_1000_rxbl_placement_pruned75.tog.tre
md5sum emp.90.min25.deblur.withtax.withtree.even1k.biom
rm -f u_c0_1.out
echo "=============="
time taskset -c 16-31,48-63 ssu -n 32 -f -m unweighted -i emp.90.min25.deblur.withtax.withtree.even1k.biom -t emp90.5000_1000_rxbl_placement_pruned75.tog.tre --mode partial --start 0 --stop 1572 -o ./u_c0_1.out
echo "rc=$?"
ls -l u_c0_1.out
md5sum u_c0_1.out
