apiVersion: v1
kind: Pod
metadata:
  name: run2
  namespace: icecube
spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
      - key: kubernetes.io/arch
        operator: Equal
        value: arm64
        effect: NoSchedule
      containers:
      - name: build
        image: almalinux:8.6
        command: ["sh", "-c", "sleep infinity"]
        resources:
           limits:
             memory: 8Gi
             cpu: 4
           requests:
             memory: 1Gi
             cpu: 2
        volumeMounts:
        - name: cvmfs-pvc
          mountPath: /cvmfs/icecube.opensciencegrid.org
      volumes:
      - name: cvmfs-pvc
        persistentVolumeClaim:
          claimName: cvmfs-icecube

