#!/usr/bin/env python

#
# Get the local storage url for the specified replica
# Use RANDOM as the first argument to get a random pick, instead of a deterministic one
#

import sys,os,random

#
# First read config file
#

try:
  with open("/dev/shm/exa_cloud_storage.conf","r") as fd:
    config_lines=fd.readlines()
except:
  print("error://missing_config_file")
  sys.exit(1)

storage_url_base=""

for cline in config_lines:
  cline = cline.strip()
  if cline.startswith("#"):
    continue
  if len(cline)==0:
    continue
  storage_url_base=cline
  break

if len(storage_url_base)<5:
  print("error://invalid_config_file")
  sys.exit(1) 

#
# Get the input argument
#

if len(sys.argv)!=3:
   print("error://missing_argument")
   sys.exit(1)

# using simiar logic as on other script, thus calling it "a hash"
hchar=sys.argv[1]
fname=os.path.normpath(sys.argv[2])

if hchar=="RANDOM":
  hostname="unknown"
  if os.environ.has_key("HOSTNAME"):
    hostname=os.environ["HOSTNAME"]
  phash = abs( hash( "%s_%i"%(hostname,random.randrange(1,10000,1)) ) )
  # get a single hex char
  hchar="%x"%(phash%16)

hashed_base_url=storage_url_base%hchar

# and we are ready to return the hashed value
print("%s%s"%(hashed_base_url,fname))

